name: o2t
favicon: null
layout_spectrum: 0.47142585297115147
typography_spectrum: 0.8584846081212163
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191919'
    - '#fdfdfd'
    - '#5f5f5f'
    - '#c1c1c1'
    - '#909090'
  brandStrength: 0.5625
  lightness: 0.7722828479018062
  saturation: 0.28736404376104474
  rhythmicContrast: 0.19636165583506227
purpose: []
